### ISSUE TITLE
Error message since on 1.15.1

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub-modules-linkpreview#10]
Hello,

Since I've updated from 1.15.0 to 1.15.1, each time I post a message or a comment (a Simple "test message" without any links inside), I have this error message that appear at the bottom of the website :

> 
> TypeError: errors is undefinedLinkPreviewEditor.prototype.setPreviewErrors@https://www.high-score.fr/assets/94f4b1a7/js/humhub.linkpreview.js?v=1.8.1:219:16
> LinkPreviewEditor.prototype.reset@https://www.high-score.fr/assets/94f4b1a7/js/humhub.linkpreview.js?v=1.8.1:158:14
> LinkPreviewEditor.prototype.init/<@https://www.high-score.fr/assets/94f4b1a7/js/humhub.linkpreview.js?v=1.8.1:122:18
> dispatch@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:3260
> add/q.handle@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:1234
> trigger@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:24991
> trigger/<@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:25597
> each@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:19:15968
> each@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:19:14428
> trigger@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:25572
> i_.prototype.clear@https://www.high-score.fr/static/js/humhub-bundle.js?v=1.8.1:221:12287
> j_.prototype.clear@https://www.high-score.fr/static/js/humhub-bundle.js?v=1.8.1:227:631
> j.prototype.init/<@https://www.high-score.fr/static/js/humhub-bundle.js?v=1.8.1:233:1049
> dispatch@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:3260
> add/q.handle@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:1234
> trigger@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:24991
> trigger/<@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:25597
> each@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:19:15968
> each@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:19:14428
> trigger@https://www.high-score.fr/static/js/humhub-app.js?v=1.8.1:30:25572
> 200@https://www.high-score.fr/static/js/humhub-bundle.js?v=1.8.1:250:5554
> q/k.status/

**Comment by yurabakhtin** [comment]
@luke- Fixed in commit https://github.com/humhub/linkpreview/pull/1

**Comment by luke-** [comment]
Should be fixed with 0.15.2
