### ISSUE TITLE
Check HumHub 1.7 support

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-linkpreview#2]

**Comment by buddh4** [comment]
Any alternative @luke- ?
![grafik](https://user-images.githubusercontent.com/9800854/96152697-1ec2b380-0f0d-11eb-8680-e31930ad4b8e.png)

**Comment by luke-** [comment]
We should migrate to: https://github.com/yiisoft/yii2-httpclient
Which is available since HH 1.3+
