### ISSUE TITLE
Problem accepting payment 

### ISSUE THREAD

**Issue by uab22** [humhub/humhub-modules-linkpreview#24]
Hello! Attempting to install this module, 'without account' and as 'Individual (private user)', I found that card is really the only relevant option from here in Norway. Having tried three different cards, now, two credit cards and one debit card, all three attempts resulted in a 'declined' message. 

This was suprising because all three cards have more than enough money on them, and are set up to be possible to use for purchases online. The experience was unusual, as it is not uncommon for me to buy things online. Unless this is something very particular that just relates to me, you may want to contact Stripe to see if there is some technical problem that prevents people who do not have iDEAL, SEPA Direct, Alipay, SOFORT, giropay or EPS, from buying this module. Thanks

**Comment by luke-** [comment]
@uab22 Can you please send an email to hello@humhub.com regarding this issue.
