### ISSUE TITLE
Bought this. Does not work

### ISSUE THREAD

**Issue by Mimanolis** [humhub/humhub-modules-linkpreview#31]
Is there an issue with the add-on we should be aware? My installaton of humhub does not produce previews in any link. Are there dependencies that should be taken care of before installation?

**Comment by luke-** [comment]
Did you activated the module? Are there any error in the logs? "Administration -> Informations -> Logging"?

**Comment by Mimanolis** [comment]
![image](https://user-images.githubusercontent.com/14232564/220137098-4971aed1-3e76-4d85-b11b-0dbb74d06a69.png)
Yes I did, placed the license key and  activated (It's in Greek, it means activated)

This is the error that appears in the logs searching for linkpreview
Error: Class "DOMDocument" not found in /var/www/snapup/protected/modules/linkpreview/vendor/symfony/dom-crawler/Crawler.php:1166
Stack trace:
#0 /var/www/snapup/protected/modules/linkpreview/vendor/symfony/dom-crawler/Crawler.php(1289): Symfony\Component\DomCrawler\Crawler->parseXhtml()
#1 /var/www/snapup/protected/modules/linkpreview/vendor/symfony/dom-crawler/Crawler.php(198): Symfony\Component\DomCrawler\Crawler->parseHtmlString()
#2 /var/www/snapup/protected/modules/linkpreview/vendor/fusonic/opengraph/src/Consumer.php(93): Symfony\Component\DomCrawler\Crawler->addHtmlContent()
#3 /var/www/snapup/protected/modules/linkpreview/vendor/fusonic/opengraph/src/Consumer.php(79): Fusonic\OpenGraph\Consumer->extractOpenGraphData()
#4 /var/www/snapup/protected/modules/linkpreview/controllers/IndexController.php(52): Fusonic\OpenGraph\Consumer->loadHtml()
#5 [internal function]: humhub\modules\linkpreview\controllers\IndexController->actionFetch()
#6 /var/www/snapup/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#7 /var/www/snapup/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams()
#8 /var/www/snapup/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction()
#9 /var/www/snapup/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#10 /var/www/snapup/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest()
#11 /var/www/snapup/index.php(25): yii\base\Application->run()
#12 {main}

Does this mean that the extension DOM is not enabled in my php?

**Comment by luke-** [comment]
Oh yes, the DOM extension seems to be missing. We are going to add the Module Requirements here.

**Comment by Mimanolis** [comment]
Thanks for the reply. Yes please add the requirements it would be very helpful

**Comment by luke-** [comment]
Thanks, i've updated the requirement. It will be available in the next version release.
