### ISSUE TITLE
Image should contain at most 255 characters

### ISSUE THREAD

**Issue by samuk** [humhub/humhub-modules-linkpreview#33]
![screenshot-vive transitiontogether org uk-2023 03 29-09_33_06](https://user-images.githubusercontent.com/400875/228486435-bf30ca48-ff8a-446a-9ee1-60c0ee432c07.png)

Is there a workaround fix for "Image should contain at most 255 characters"

**Comment by samuk** [comment]
Thanks..

**Comment by cbrophy78** [comment]
Was this closed cus it is working as expected? and if so is there a way to mitigate it?
