### ISSUE TITLE
Remove 'error' text on internal links

### ISSUE THREAD

**Issue by samuk** [humhub/humhub-modules-linkpreview#35]
When I link to other internal links on my humhub instance it displays 'error' in the link preview

![error](https://user-images.githubusercontent.com/400875/233103920-6fcf03b3-518d-4042-b93d-7e2a2500469a.png)

I understand that these can't be rendered completely, but could we remove the word 'Error' from the preview?

**Comment by gevorgmansuryan** [comment]
https://hub.transition-space.org/s/welcome-space/survey/show/single?id=8

**Comment by luke-** [comment]
Will be fixed with 2.0.1 release
