### ISSUE TITLE
Alert box showing "asdf"

### ISSUE THREAD

**Issue by marc-farre** [humhub/humhub-modules-linkpreview#36]
After adding a comment to a global content and submitting a form containing this comment, I got an alert box:
![image](https://user-images.githubusercontent.com/23310825/236673741-22f790d3-e45c-45f4-bc09-f334c81e2708.png)

Isn't it a forgotten test in `humhub.linkpreview.js`?
```js
        this.$.closest('form').on('submit', function () {
            alert('asdf');
        });
```

**Comment by gevorgmansuryan** [comment]
![Image](https://github.com/humhub/linkpreview-issues/assets/11891855/6684df63-a0fb-44e1-adaa-c9bc8bbac624)

seems already 6 years it works like this :)
