### ISSUE TITLE
Favicon is replaced by new one when posting a link

### ISSUE THREAD

**Issue by Reuns** [humhub/humhub-modules-linkpreview#4]
Hi there.
When adding a link in a post, the preview works well, but the favicon is changed by the favicon of the linked website.
That's not a big deal but it's disturbing seeing the youtube favicon instead of the good one.

Thanks for your help.

**Comment by buddh4** [comment]
Can you provide a step by step example?

**Comment by Reuns** [comment]
Sure 👍 
I copy the URI of this issue (https://github.com/humhub/humhub-modules-linkpreview/issues/4#issuecomment-724731983)
I paste-it in a new content form (no matter if it's a space, personnal wall or in a comment ... it "works" in all these case).
The module analyze the target then show the preview. At the same time, my favicon become the github logo.

Hope it's clear enough.
Do you need screenshots ?

**Comment by Reuns** [comment]
You'll find a short clip here :
https://youtu.be/LUliWUoELuc

**Comment by buddh4** [comment]
Thanks should be fixed in the current marketplace version.
