### ISSUE TITLE
Error saving an image: Image should contain at most 255 characters.

### ISSUE THREAD

**Issue by samuk** [humhub/humhub-modules-linkpreview#40]
### What steps will reproduce the problem?

Paste this link into a humhub instance with the link preview module enabled https://www.cbsnews.com/news/climate-change-air-quality-unhealthy-wildfires-first-street/

### What is the expected result?

The image from the article is displayed

### What do you get instead?

 This link preview will not be saved because of errors:    Image should contain at most 255 characters.

![image255](https://github.com/humhub/humhub/assets/400875/45ac9387-9777-4db5-b896-f1e063864e19)

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | Version: 1.15.0
| PHP version      | 
| Operating system | Debian

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

**Comment by marc-farre** [comment]
@luke- fixed in PR https://github.com/humhub/linkpreview/pull/20

**Comment by luke-** [comment]
@marc-farre Thanks!

Fixed with 2.0.2
