### ISSUE TITLE
[Demo] Module not included in demo hosting

### ISSUE THREAD

**Issue by schlagmichdoch** [humhub/humhub-modules-linkpreview#42]
I'd like to test this module.

In your marketplace description it says: "Tip! Try this module in our demo hosting."

I have then created a demo instance via https://saas.humhub.com/en/create but the link preview module is not included. If I wanted to add it via the demo marketplace it requests payment as it does on my own instance.

Do I miss anything?

**Comment by luke-** [comment]
There shouldn't  be any problems here.

@yurabakhtin can you check that?

**Comment by yurabakhtin** [comment]
@luke- I have reviewed the code related to the module installing from Marketplace but I couldn't find issues there.
Then I have also created a demo server and the module "Link Preview" is installed for me without any problems:

https://yurabakh-demo.humhub.com/s/welcome-space/

![test-linkpreview](https://github.com/user-attachments/assets/e97b8f84-b577-43dd-8c84-d5c99c68cbc6)

**Comment by schlagmichdoch** [comment]
Have you changed anything? Apparently, I can now install it without any payment. Thanks!

**Comment by luke-** [comment]
Yes, we had temporarily blocked the module in the demo hosting because we had a problem with the PHP prerequisite.

In the meantime, it should be free again as usual in our SaaS hosting.
