### ISSUE TITLE
Ignore mailto links

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-linkpreview#7]
[Zend\Http\Exception\InvalidArgumentException] Zend\Uri\Exception\InvalidUriPartException: Scheme "mailto" is not valid or is not accepted by Zend\Uri\Http in /srv/humhub/protected/vendor/zendframework/zend-uri
Stack trace:
#0 /srv/humhub/protected/vendor/zendframework/zend-uri/src/Uri.php(284): Zend\Uri\Uri->setScheme('mailto')
#1 /srv/humhub/protected/vendor/zendframework/zend-uri/src/Http.php(214): Zend\Uri\Uri->parse('mailto:some-...')
#2 /srv/humhub/protected/vendor/zendframework/zend-uri/src/Uri.php(142): Zend\Uri\Http->parse('mailto:some-...')
#3 /srv/humhub/protected/vendor/zendframework/zend-http/src/Request.php(203): Zend\Uri\Uri->__construct('mailto:some-...')
#4 /srv/humhub/protected/vendor/zendframework/zend-http/src/Client.php(317): Zend\Http\Request->setUri('mailto:some-...')
#5 /srv/humhub/protected/vendor/zendframework/zend-http/src/Client.php(143): Zend\Http\Client->setUri('mailto:some-...')
#6 /srv/www/htdocs/suse/modules/linkpreview/controllers/IndexController.php(37): Zend\Http\Client->__construct('mailto:some-...', Array)
#7 [internal function]: humhub\modules\linkpreview\controllers\IndexController->actionFetch()
#8 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /srv/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#10 /srv/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('fetch', Array)
#11 /srv/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('linkpreview/ind...', Array)
#12 /srv/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))

**Comment by buddh4** [comment]
Fixed in v1.14
