### ISSUE TITLE
Chinese and Japanese character problems

### ISSUE THREAD

**Issue by luke-** [humhub/humhub-modules-linkpreview#9]
Working Example URL e.g. with chinese characters: https://www.sina.com.cn/
Failing url: https://m.youtube.com/watch?v=2x5Z11Bi27w&feature=youtu.be

![image](https://user-images.githubusercontent.com/4736168/111813987-377b2f00-88da-11eb-85c9-404ed319f43c.png)

**Comment by yurabakhtin** [comment]
@luke- MR https://git.humhub.org/modules/linkpreview/-/merge_requests/2

<img width="665" alt="test_diff_lang" src="https://user-images.githubusercontent.com/6995524/112100874-d80d6f80-8bb6-11eb-9450-3dd496ef4713.png">

**Comment by yurabakhtin** [comment]
@luke- First solution was not ideal for several site, so I have done a new solution in commit https://git.humhub.org/modules/linkpreview/-/merge_requests/2/diffs?commit_id=3ca01d619b30553da1ad2a8b919d2711b44befaa

I tested with the following urls:

- https://www.youtube.com/watch?app=desktop&v=2x5Z11Bi27w&feature=youtu.be
- https://www.amazon.co.jp
- https://homestayireland.ie/ja/study_english_j.html
- https://ja.wikipedia.org/wiki/アイルランド系アメリカ人
- https://mail.ru/
- https://www.google.com
- http://spotify.com/ru-ru
- https://hygiene-shop.nl/hygiene-dispensers/

<img width="663" alt="test_langs" src="https://user-images.githubusercontent.com/6995524/112143130-84b41500-8be8-11eb-94ac-4fc651f6191b.png">

**Comment by luke-** [comment]
@yurabakhtin Great!
